### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by iamsile** [saltypaul/Seq2Seq-Chatbot#1]
Hi,@saltypaul , When I use model to predict, there are some bugs in it. Like this:

Traceback (most recent call last):
  File "build_model.py", line 98, in <module>
    convB = cbot.utter(conva)
  File "/Users/xxx/Seq2Seq-Chatbot/src/chatbot.py", line 17, in utter
    convb_idxs = self.model.utter(conva_idxs, conva_mask)
  File "/Users/xxx/Seq2Seq-Chatbot/src/seq2seq.py", line 184, in utter
    return self._utter(encoderInputs, encoderMask ,decoderInputs)
  File "/Library/Python/2.7/site-packages/Theano-0.9.0dev1-py2.7.egg/theano/compile/function_module.py", line 821, in __call__
    allow_downcast=s.allow_downcast)
  File "/Library/Python/2.7/site-packages/Theano-0.9.0dev1-py2.7.egg/theano/tensor/type.py", line 178, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/Users/xxx/Seq2Seq-Chatbot/src/seq2seq.py:171" at index 1 (0-based)', 'Wrong number of dimensions: expected 2, got 1 with shape (50,).')

and then I modify the encoderMask' shape, but also can't fix.

Can you tell me what's wrong with it?  Thank you very much!

**Comment by damientseng** [comment]
Sorry for that, actually there are some bugs with the validation input. Now this should work : ))

**Comment by iamsile** [comment]
@saltypaul, Thank you very much! It works and I also know where is wrong in my code! Thanks!
